### ISSUE TITLE
[Feature Request] LAMBDA

### ISSUE THREAD

**Issue by yardenas** [PKU-Alignment/omnisafe#139]
### Required prerequisites

- [X] I have searched the [Issue Tracker](https://github.com/PKU-MARL/omnisafe/issues) and [Discussions](https://github.com/PKU-MARL/omnisafe/discussions) that this hasn't already been reported. (+1 or comment there if it has.)
- [X] Consider asking first in a [Discussion](https://github.com/PKU-MARL/omnisafe/discussions/new).

### Motivation

I'm the author of LAMBDA, I can contribute my implementation, how should I proceed?

### Solution

Implementation of LAMBDA, in pytorch (if I'm not mistaken). I also have a TF and JAX implementations.

**Comment by zmsn-2077** [comment]
`LAMBDA` is an excellent algorithm and if you want to add `LAMBDA` to `omnisafe`, you need to implement the algorithm in the `PyTorch` framework, which is a relatively large amount of work. Many students around me who study safe reinforcement learning have also tried to use `LAMBDA` as a baseline in their papers, but `LAMBDA` is only available in `TensorFlow`, which is probably one of the reasons that prevent this algorithm from being used by more people.

We suggest forking the `omnisafe` repository and implementing `LAMBDA` in the **branch:dev** current framework with a Lambda implementation in PyTorch and propose a PR(Pull Requests), and then we will add Lambda to `omnisafe` as soon as possible to allow more researchers to use the algorithm.

**Comment by zmsn-2077** [comment]
Hello @yardenas. Some attempts are underway. @hdadong has modified `LAMBDA` to the PyTorch version, but the correctness is yet to be verified. We will make the code public in advance and open a new branch named dev-lambda in `omnisafe`. We sincerely hope that you can also participate in the performance verification of lambda. On the one hand, it will reduce your workload of rewriting a PyTorch version, and we also hope that our reproduction can be affirmed by the author of the algorithm, that is, you. At the same time, we will add a reference to the original repo of [LAMBDA](https://github.com/yardenas/la-mbda) in the comments of the code.

**Comment by yardenas** [comment]
Great! Very happy to hear that, let me know when and how I can contribute. BTW, there's another JAX implementation of LAMBDA here: https://github.com/yardenas/safe-adaptation-agents/tree/main/safe_adaptation_agents/agents/model_based/la_mbda
