### ISSUE TITLE
[Feature Request] APPO

### ISSUE THREAD

**Issue by calico-1226** [PKU-Alignment/omnisafe#235]
### Required prerequisites

- [X] I have searched the [Issue Tracker](https://github.com/OmniSafeAI/omnisafe/issues) and [Discussions](https://github.com/OmniSafeAI/omnisafe/discussions) that this hasn't already been reported. (+1 or comment there if it has.)
- [X] Consider asking first in a [Discussion](https://github.com/OmniSafeAI/omnisafe/discussions/new).

### Motivation

I am the author of Augmented Proximal Policy Optimization for Safe Reinforcement Learning (APPO), and I will upload algorithm code that is consistent with the Omnisafe interface.

### Solution

I will submit the implementation of APPO as soon as possible.

**Comment by zmsn-2077** [comment]
The act of contributing new algorithms is highly advocated.

**Comment by Eureke01** [comment]
Hello, I would like to know where the code section is for "Augmented Proximal Policy Optimization for Safe Reinforcement Learning" (APPO).Has this part of the code been uploaded?

**Comment by Gaiejj** [comment]
We will update this issue at #313
