### ISSUE TITLE
[Question] Why average actor's gradient in DDPG but not in SAC ?

### ISSUE THREAD

**Issue by Gaiejj** [PKU-Alignment/omnisafe#252]
### Required prerequisites

- [X] I have read the documentation <https://omnisafe.readthedocs.io>.
- [X] I have searched the [Issue Tracker](https://github.com/PKU-Alignment/omnisafe/issues) and [Discussions](https://github.com/PKU-Alignment/omnisafe/discussions) that this hasn't already been reported. (+1 or comment there if it has.)
- [X] Consider asking first in a [Discussion](https://github.com/PKU-Alignment/omnisafe/discussions/new).

### Questions

We utilize `distributed.avg_grads` to average the gradients of the actor and critic network in DDPG, but not in SAC's actor network. In fact, due to the current lack of support for off-policy algorithms in the A3C parallel paradigm (preliminary checks are present in the `omnisafe/algorithms/algo_wrapper.py` file, and off-policy algorithms will not initiate training in the A3C parallel paradigm), in practice, gradient averaging is not performed during the training process of off-policy algorithms. A future pull request will removes redundant code, enhances readability, and does not affect the performance of the algorithm.

**Comment by Gaiejj** [comment]
Pull request #253 solve it.

**Comment by zmsn-2077** [comment]
Already approve PR #253.
