### ISSUE TITLE
[Question] The cost Q-value network is repeatedly add_module

### ISSUE THREAD

**Issue by guanjiayi** [PKU-Alignment/omnisafe#259]
### Required prerequisites

- [X] I have read the documentation <https://omnisafe.readthedocs.io>.
- [X] I have searched the [Issue Tracker](https://github.com/PKU-Alignment/omnisafe/issues) and [Discussions](https://github.com/PKU-Alignment/omnisafe/discussions) that this hasn't already been reported. (+1 or comment there if it has.)
- [X] Consider asking first in a [Discussion](https://github.com/PKU-Alignment/omnisafe/discussions/new).

### Questions

- [ ] The cost_critic network is repeatedly called with add_module during the creation process in the classes ConstraintActorQCritic and QCritic.

In the class of QCritic: ` self.add_module(f'critic_{idx}',critic)`
In the class of ConstraintActorQCritic: `self.add_moudle('cost_critic',self.cost_ritic)`

**Comment by zmsn-2077** [comment]
Feel free to ask to reopen this if you have more questions.
