### ISSUE TITLE
[Feature Request] Will there be any consideration for supporting MetaDriver recently?

### ISSUE THREAD

**Issue by yinglinmonian** [PKU-Alignment/omnisafe#262]
### Required prerequisites

- [X] I have searched the [Issue Tracker](https://github.com/PKU-Alignment/omnisafe/issues) and [Discussions](https://github.com/PKU-Alignment/omnisafe/discussions) that this hasn't already been reported. (+1 or comment there if it has.)
- [X] Consider asking first in a [Discussion](https://github.com/PKU-Alignment/omnisafe/discussions/new).

### Motivation

OmniSafe is a meaningful repository that offers a collection of Safe-related algorithms, significantly aiding scientific research. I would like to know if the developers have recently considered supporting the [MetaDrive](https://github.com/metadriverse/metadrive), which also provides some constraint-related tasks.

<img width="852" alt="image" src="https://github.com/PKU-Alignment/omnisafe/assets/43464701/8403a299-184e-4260-b663-46eb2a9f1135">
<img width="947" alt="image" src="https://github.com/PKU-Alignment/omnisafe/assets/43464701/99382ede-8c9e-4b2a-91a5-0ff75a16596a">

**Comment by Gaiejj** [comment]
Thank you so much for the recognition of OmniSafe! We find meta drive to be a meaningful safe reinforcement learning task. We'll be providing a pull request to add support for it and share the algorithm's performance results. Please stay tuned for our upcoming pull request.
