### ISSUE TITLE
[Feature Request] update CMDP/Wrapper API to gymnasium API 

### ISSUE THREAD

**Issue by luigiberducci** [PKU-Alignment/omnisafe#265]
### Required prerequisites

- [X] I have searched the [Issue Tracker](https://github.com/PKU-Alignment/omnisafe/issues) and [Discussions](https://github.com/PKU-Alignment/omnisafe/discussions) that this hasn't already been reported. (+1 or comment there if it has.)
- [ ] Consider asking first in a [Discussion](https://github.com/PKU-Alignment/omnisafe/discussions/new).

### Motivation

I had some issue with the fact that the reset method does not match the signature of gymnasium API.
In particular, the argument `options` is missing.

### Solution

Update the signature as
`reset(
        self,
        *,
        seed: int | None = None,
        options: dict[str, Any] | None = None,
    ) -> tuple[ObsType, dict[str, Any]]:`

**Comment by Gaiejj** [comment]
Pull request #266 would support this new interface. You can check whether it meets your requirement and feel free to review it.

**Comment by luigiberducci** [comment]
Thanks, I will look into it!
