### ISSUE TITLE
[Question] 

### ISSUE THREAD

**Issue by Obnayuf** [PKU-Alignment/omnisafe#281]
### Required prerequisites

- [X] I have read the documentation <https://omnisafe.readthedocs.io>.
- [X] I have searched the [Issue Tracker](https://github.com/PKU-Alignment/omnisafe/issues) and [Discussions](https://github.com/PKU-Alignment/omnisafe/discussions) that this hasn't already been reported. (+1 or comment there if it has.)
- [X] Consider asking first in a [Discussion](https://github.com/PKU-Alignment/omnisafe/discussions/new).

### Questions

Thanks for your repo. It does help me a lot. I just wanna know how to use both parallel and multi-gpu in "train_policy.py"?

**Comment by Gaiejj** [comment]
The current version of OmniSafe does not support specifying multiple GPUs for parallel ``A3C`` training using the ``train_policy.py`` script. This feature is actively under development and is expected to be available recently through a Pull Request.

**Comment by Gaiejj** [comment]
#282 resolves it.
