### ISSUE TITLE
[Question] 

### ISSUE THREAD

**Issue by QionghuaLiao** [PKU-Alignment/omnisafe#283]
### Required prerequisites

- [X] I have read the documentation <https://omnisafe.readthedocs.io>.
- [X] I have searched the [Issue Tracker](https://github.com/PKU-Alignment/omnisafe/issues) and [Discussions](https://github.com/PKU-Alignment/omnisafe/discussions) that this hasn't already been reported. (+1 or comment there if it has.)
- [X] Consider asking first in a [Discussion](https://github.com/PKU-Alignment/omnisafe/discussions/new).

### Questions

Hi there,

Thank you so much for your valuable contributions on SRL!

I'm currently working with the PPOLag algorithm and I've noticed that it only supports Box-type Observation apace and Action space. I would like to know how I can use this algorithm with Discrete-type Observation space and Action space.

Additionally, I'm curious to know if all the SRL algorithms provided by this project default to supporting only Box-type Observation space and Action space. If there are any workarounds or alternative methods to handle Discrete spaces within this library, I would greatly appreciate any guidance or suggestions.

Thank you for your time and assistance!

**Comment by Gaiejj** [comment]
At present, OmniSafe does not support models with ``discrete action spaces`` and ``discrete observation spaces``. In the spirit of contributing to the community as an open-source software library, we plan to introduce interfaces for environments with discrete action and observation spaces in the near future. We intend to implement this feature using ``PPO``, using typical environments with discrete actions and observations from the ``Gymnasium`` as examples.

**Comment by Gaiejj** [comment]
#286 supports this feature. Feel free to use it or give us a review.

**Comment by Gaiejj** [comment]
Closed due to no further questions. You're welcome to reopen it if you happen to have more issues.
