### ISSUE TITLE
[Feature Request] Tutorial of customizing environment

### ISSUE THREAD

**Issue by Gaiejj** [PKU-Alignment/omnisafe#291]
### Required prerequisites

- [X] I have searched the [Issue Tracker](https://github.com/PKU-Alignment/omnisafe/issues) and [Discussions](https://github.com/PKU-Alignment/omnisafe/discussions) that this hasn't already been reported. (+1 or comment there if it has.)
- [X] Consider asking first in a [Discussion](https://github.com/PKU-Alignment/omnisafe/discussions/new).

### Motivation

OmniSafe currently has more issues and discussions involving the running of customized environments. We decided to provide a **more detailed tutorial and examples** of customized environments for users to understand OmniSafe's wrapper and adapter features. This tutorial is under development.

**Comment by jyao97** [comment]
Hello, would you like to share any progress on this tutorial? Thanks a lot!

**Comment by Gaiejj** [comment]
We are currently in the iterative development process and expect to be ready within a week. Thank you very much for your support.

**Comment by jyao97** [comment]
> We are currently in the iterative development process and expect to be ready within a week. Thank you very much for your support.

Thank you! I look forward to reading it!

**Comment by Gaiejj** [comment]
@jyao97 Hello, We have released environment customization tutorials. Please feel free to use it and report any more problems. https://github.com/PKU-Alignment/omnisafe/tree/main/tutorials

**Comment by Gaiejj** [comment]
We will update the code library for the customized environment interface to PyPI within 1-3 days. Before that, please choose to install from the source code when running the tutorial.

**Comment by jyao97** [comment]
> @jyao97 Hello, We have released environment customization tutorials. Please feel free to use it and report any more problems. https://github.com/PKU-Alignment/omnisafe/tree/main/tutorials

Thank you so much! Great work!

**Comment by Gaiejj** [comment]
We have released the new version of our project to PyPI, i.e., `0.5.0`. However, if you running `pip install omnisafe` directly in colab, a warning will be raised:
```bash
WARNING: The following packages were previously imported in this runtime:
  [numpy]
You must restart the runtime in order to use newly installed versions.

Restarting will lose all runtime state, including local variables.
```
Simply rerun the colab page can resolve this issue.
