### ISSUE TITLE
Curriculum Learning with Omnisafe or Safe-Policy-Optimization

### ISSUE THREAD

**Issue by fardinabbasi** [PKU-Alignment/omnisafe#298]
### Required prerequisites

- [X] I have read the documentation <https://omnisafe.readthedocs.io>.
- [X] I have searched the [Issue Tracker](https://github.com/PKU-Alignment/omnisafe/issues) and [Discussions](https://github.com/PKU-Alignment/omnisafe/discussions) that this hasn't already been reported. (+1 or comment there if it has.)
- [x] Consider asking first in a [Discussion](https://github.com/PKU-Alignment/omnisafe/discussions/new).

### Questions

Given the varying levels of difficulty within Safety-Gymnasium environments, can curriculum learning be implemented to progressively train agents, starting with simpler environments and gradually advancing to more complex ones?

Please also address this question in the context of the Safe-Policy-Optimization project.
Thanks

**Comment by Gaiejj** [comment]
Our recent cursory investigation into curriculum learning posits their significance in achieving a safer policy. Currently, OmniSafe and SafePO do not endorse this feature. If you're an expert in this domain, we cordially invite you to initiate a Pull Request like #300 . We'd be more than pleased to conduct a review.

**Comment by Gaiejj** [comment]
Closed due to no further questions. You're welcome to reopen it if you happen to have more issues.
