### ISSUE TITLE
[Question] Customised Environment Carla-gym

### ISSUE THREAD

**Issue by lishizhen1412** [PKU-Alignment/omnisafe#305]
### Required prerequisites

- [X] I have read the documentation <https://omnisafe.readthedocs.io>.
- [X] I have searched the [Issue Tracker](https://github.com/PKU-Alignment/omnisafe/issues) and [Discussions](https://github.com/PKU-Alignment/omnisafe/discussions) that this hasn't already been reported. (+1 or comment there if it has.)
- [X] Consider asking first in a [Discussion](https://github.com/PKU-Alignment/omnisafe/discussions/new).

### Questions

This tool has greatly facilitated scientific research! Can the customised environment be used to train and evaluate algorithms using Carla-gym, the simulation environment of the Carla simulator?

**Comment by Gaiejj** [comment]
This task seems to be used for multi-agent reinforcement learning. Currently, OmniSafe does not support multi-agent reinforcement learning algorithms. We will consider integrating them in subsequent updates and will remind you under this issue.

**Comment by Gaiejj** [comment]
/home/yangyaodong/projects/resist/align-anything/local_scirpts
