### ISSUE TITLE
[Question] How to use the Dockerfile

### ISSUE THREAD

**Issue by chenyinlin1** [PKU-Alignment/omnisafe#308]
### Required prerequisites

- [X] I have read the documentation <https://omnisafe.readthedocs.io>.
- [X] I have searched the [Issue Tracker](https://github.com/PKU-Alignment/omnisafe/issues) and [Discussions](https://github.com/PKU-Alignment/omnisafe/discussions) that this hasn't already been reported. (+1 or comment there if it has.)
- [X] Consider asking first in a [Discussion](https://github.com/PKU-Alignment/omnisafe/discussions/new).

### Questions

Hello Author. I want to create an image using a Dockerfile file. But after using the command 'docker build -t test/omnisafe:v0 . ' after that, an error occurs, and after trying to change it, there are still other errors reported, is there something wrong with the way I'm using it?
![image](https://github.com/PKU-Alignment/omnisafe/assets/148037200/b01683f0-e511-4294-9701-b868c45a1719)

**Comment by Gaiejj** [comment]
We have successfully reproduced the issue you encountered and found that by removing the ``--no-build-isolation`` parameter from ``line 22`` of the Makefile, the image can be successfully built with the command 
```bash
docker build --target base --tag omnisafe:latest .
```

**Comment by chenyinlin1** [comment]
Thanks

**Comment by Gaiejj** [comment]
Closed due to no further questions. You're welcome to reopen it if you happen to have more issues.
