### ISSUE TITLE
[Question] Where is CVPO?

### ISSUE THREAD

**Issue by JiwenJ** [PKU-Alignment/omnisafe#311]
### Required prerequisites

- [X] I have read the documentation <https://omnisafe.readthedocs.io>.
- [X] I have searched the [Issue Tracker](https://github.com/PKU-Alignment/omnisafe/issues) and [Discussions](https://github.com/PKU-Alignment/omnisafe/discussions) that this hasn't already been reported. (+1 or comment there if it has.)
- [X] Consider asking first in a [Discussion](https://github.com/PKU-Alignment/omnisafe/discussions/new).

### Questions

Hello, I believe there was a CVPO implementation in issue #57. I'm curious as to why it was removed.

**Comment by Gaiejj** [comment]
As previously discussed, we found that CVPO needs algorithmic adjustments to the environment's configuration (i.e., removing the randomness of the environment layer). We conducted detailed experiments and found that CVPO's performance on random layers was unsatisfactory. 

Relevant experimental evidence has also been disclosed in the SafeRL research. You can refer to the paper published at ICLR 2024: [Off-Policy Primal-Dual Safe Reinforcement Learning](https://openreview.net/forum?id=vy42bYs1Wo).

<img width="603" alt="image" src="https://github.com/PKU-Alignment/omnisafe/assets/108712610/5b93a633-8bb6-4985-b898-a797ad5d26cb">

Anyway, we are currently trying to upload the requirements for customizing this algorithm's environment further to Safety-Gymnasium modifications to facilitate community use.

If you have any comments or ideas, feel free to discuss them further.

**Comment by Gaiejj** [comment]
Since there has been no response for a long time, we will close this issue. Please feel free to reopen it if you encounter any new problems!
