### ISSUE TITLE
输出视频问题

### ISSUE THREAD

**Issue by Eureke01** [PKU-Alignment/omnisafe#329]
### Required prerequisites

- [X] I have read the documentation <https://omnisafe.readthedocs.io>.
- [X] I have searched the [Issue Tracker](https://github.com/PKU-Alignment/omnisafe/issues) and [Discussions](https://github.com/PKU-Alignment/omnisafe/discussions) that this hasn't already been reported. (+1 or comment there if it has.)
- [ ] Consider asking first in a [Discussion](https://github.com/PKU-Alignment/omnisafe/discussions/new).

### Questions

我在使用python evaluate_saved_policy.py命令时产生如下错误，请问该怎么解决？
![image](https://github.com/PKU-Alignment/omnisafe/assets/104348087/0450b4e6-43b5-479a-9ff7-f2f3438600d1)

**Comment by zhou-ting-hub** [comment]
![image](https://github.com/PKU-Alignment/omnisafe/assets/80151423/6e4b0a8c-ffac-41d9-bac8-d8a91250fe45)
我把它注释掉了，我的结果是数据，可以在环境里保存到csv文件，我不知道这个MP4是啥，你需不需要这个MP4

**Comment by Eureke01** [comment]
@zhou-ting-hub 我想看智能体在环境中的行为是怎样的，输出一个MP4视频看看。

**Comment by Eureke01** [comment]
![image](https://github.com/PKU-Alignment/omnisafe/assets/104348087/a588b4fa-d63e-4397-9e2c-45ae054d1a54)
这个问题来源于mujoco？请问该如何解决

**Comment by Gaiejj** [comment]
Sure, it is a issue of mujoco in headless server. you can try: `export MUJOCO_GL=osmesa` in your bash. Then you can run `python evaluate_saved_policy.py`.

**Comment by Eureke01** [comment]
> Sure, it is a issue of mujoco in headless server. you can try: `export MUJOCO_GL=osmesa` in your bash. Then you can run `python evaluate_saved_policy.py`.

![image](https://github.com/PKU-Alignment/omnisafe/assets/104348087/64b52ac4-f793-41d7-8684-71ce0f6c9dd0)
在执行`export MUJOCO_GL=osmesa`之后产生了新的错误，请问这个错误应该如何解决？

**Comment by Gaiejj** [comment]
I'm sorry I couldn't reproduce your issue. I wonder if it's related to your operating system and the version installed.
- Get operating system information
```python
import sys
print(sys.version, sys.platform)
```

- Get Python package information
```bash
python3 -m pip list
```

**Comment by Eureke01** [comment]
> I'm sorry I couldn't reproduce your issue. I wonder if it's related to your operating system and the version installed.
> 
> * Get operating system information
> 
> ```python
> import sys
> print(sys.version, sys.platform)
> ```
> 
> * Get Python package information
> 
> ```shell
> python3 -m pip list
> ```

(omnisafe) root@user-Super-Server:/workspace# python sys.py 
3.10.14 (main, Mar 21 2024, 16:24:04) [GCC 11.2.0] linux
(omnisafe) root@user-Super-Server:/workspace# python3 -m pip list
Package                       Version      Editable project location
----------------------------- ------------ -------------------------
absl-py                       1.4.0
aiohttp                       3.9.3
aiosignal                     1.2.0
alabaster                     0.7.16
anyio                         3.5.0
appdirs                       1.4.4
asttokens                     2.0.5
async-timeout                 4.0.3
attrs                         23.1.0
Babel                         2.11.0
beautifulsoup4                4.12.3
blinker                       1.6.2
Bottleneck                    1.3.7
Brotli                        1.0.9
cachetools                    4.2.2
certifi                       2024.2.2
cffi                          1.16.0
charset-normalizer            2.0.4
click                         8.1.7
cloudpickle                   3.0.0
colorama                      0.4.6
comm                          0.2.1
commonmark                    0.9.1
contourpy                     1.2.0
cryptography                  42.0.5
cycler                        0.11.0
debugpy                       1.6.7
decorator                     5.1.1
docker-pycreds                0.4.0
docutils                      0.20.1
exceptiongroup                1.2.0
executing                     0.8.3
Farama-Notifications          0.0.4
fastjsonschema                2.16.2
ffmpy                         0.3.2
filelock                      3.13.1
fonttools                     4.51.0
frozenlist                    1.4.0
future                        0.18.3
gdown                         5.1.0
gitdb                         4.0.7
GitPython                     3.1.37
glfw                          2.7.0
gmpy2                         2.1.2
google-auth                   2.22.0
google-auth-oauthlib          0.5.2
greenlet                      3.0.1
grpcio                        1.48.2
gymnasium                     0.28.1
gymnasium-robotics            1.2.2
h11                           0.14.0
idna                          3.4
imageio                       2.33.1
imageio-ffmpeg                0.4.9
imagesize                     1.4.1
importlib-metadata            7.0.1
ipykernel                     6.28.0
ipython                       8.20.0
jax-jumpy                     1.0.0
jedi                          0.18.1
Jinja2                        3.1.3
jsonschema                    4.19.2
jsonschema-specifications     2023.7.1
jupyter-cache                 1.0.0
jupyter_client                8.6.0
jupyter_core                  5.5.0
kiwisolver                    1.4.4
latexcodec                    2.0.1
livereload                    2.6.3
Markdown                      3.4.1
markdown-it-py                3.0.0
MarkupSafe                    2.1.3
matplotlib                    3.8.4
matplotlib-inline             0.1.6
mdit-py-plugins               0.4.0
mdurl                         0.1.0
mkl-fft                       1.3.8
mkl-random                    1.2.4
mkl-service                   2.4.0
moviepy                       1.0.3
mpmath                        1.3.0
mujoco                        2.3.3
multidict                     6.0.4
myst-nb                       1.1.0
myst-parser                   2.0.0
nbclient                      0.8.0
nbformat                      5.9.2
nest-asyncio                  1.6.0
networkx                      3.1
numexpr                       2.8.7
numpy                         1.23.5
oauthlib                      3.2.2
omnisafe                      0.5.0        /workspace/omnisafe
packaging                     23.2
pandas                        2.0.3
parso                         0.8.3
pathtools                     0.1.2
pettingzoo                    1.24.3
pexpect                       4.8.0
pillow                        10.2.0
pip                           23.3.1
platformdirs                  3.10.0
proglog                       0.1.9
prompt-toolkit                3.0.43
protobuf                      3.20.3
psutil                        5.9.0
ptyprocess                    0.7.0
pure-eval                     0.2.2
pyasn1                        0.4.8
pyasn1-modules                0.2.8
pybtex                        0.24.0
pybtex-docutils               1.0.3
pycparser                     2.21
pyenchant                     3.2.2
pygame                        2.1.0
Pygments                      2.15.1
PyJWT                         2.4.0
PyOpenGL                      3.1.7
pyOpenSSL                     24.0.0
pyparsing                     3.0.9
PySocks                       1.7.1
python-dateutil               2.8.2
pytz                          2023.3.post1
PyYAML                        6.0.1
pyzmq                         25.1.2
referencing                   0.30.2
requests                      2.31.0
requests-oauthlib             1.3.0
rich                          12.5.1
rpds-py                       0.10.6
rsa                           4.7.2
safety-gymnasium              1.0.0
seaborn                       0.12.2
sentry-sdk                    1.9.0
setproctitle                  1.2.2
setuptools                    68.2.2
shellingham                   1.5.0
six                           1.16.0
smmap                         4.0.0
sniffio                       1.3.0
snowballstemmer               2.2.0
soupsieve                     2.5
Sphinx                        7.3.7
sphinx-autobuild              2024.4.16
sphinx-autodoc-typehints      2.1.0
sphinx-copybutton             0.5.2
sphinxcontrib-applehelp       1.0.2
sphinxcontrib-bibtex          2.6.2
sphinxcontrib-devhelp         1.0.2
sphinxcontrib-htmlhelp        2.0.0
sphinxcontrib-jsmath          1.0.1
sphinxcontrib-qthelp          1.0.3
sphinxcontrib-serializinghtml 1.1.10
sphinxcontrib-spelling        4.3.0
SQLAlchemy                    2.0.25
stack-data                    0.2.0
starlette                     0.37.2
sympy                         1.12
tabulate                      0.9.0
tensorboard                   2.12.1
tensorboard-data-server       0.7.0
tensorboard-plugin-wit        1.8.1
tomli                         2.0.1
torch                         2.0.1
torchvision                   0.15.2
tornado                       6.3.3
tqdm                          4.65.0
traitlets                     5.7.1
triton                        2.0.0
typer                         0.9.0
typing_extensions             4.9.0
tzdata                        2023.3
unicodedata2                  15.1.0
urllib3                       1.26.18
uvicorn                       0.29.0
wandb                         0.16.5
watchfiles                    0.21.0
wcwidth                       0.2.5
websockets                    12.0
Werkzeug                      2.3.8
wheel                         0.41.2
xmltodict                     0.13.0
yarl                          1.9.3
zipp                          3.17.0
这是系统和版本，老师您看一下该问题是否和版本相关？

**Comment by Gaiejj** [comment]
@Eureke01 Hello, let us discuss this problem in #331 .
