### ISSUE TITLE
How to use a model that has already been trained through omnisafe?

### ISSUE THREAD

**Issue by Eureke01** [PKU-Alignment/omnisafe#333]
### Required prerequisites

- [X] I have read the documentation <https://omnisafe.readthedocs.io>.
- [X] I have searched the [Issue Tracker](https://github.com/PKU-Alignment/omnisafe/issues) and [Discussions](https://github.com/PKU-Alignment/omnisafe/discussions) that this hasn't already been reported. (+1 or comment there if it has.)
- [ ] Consider asking first in a [Discussion](https://github.com/PKU-Alignment/omnisafe/discussions/new).

### Questions

Thank you for your work! How should I load a trained model? For example, if I have trained a model using the PPO algorithm in omnisafe, how should I use it in the environment?

**Comment by Gaiejj** [comment]
Hello. You can refer to `examples/evaluate_saved_policy.py`.
