### ISSUE TITLE
 cuda-based omnisafe environment

### ISSUE THREAD

**Issue by liu-yuntao** [PKU-Alignment/omnisafe#336]
### Required prerequisites

- [X] I have read the documentation <https://omnisafe.readthedocs.io>.
- [X] I have searched the [Issue Tracker](https://github.com/PKU-Alignment/omnisafe/issues) and [Discussions](https://github.com/PKU-Alignment/omnisafe/discussions) that this hasn't already been reported. (+1 or comment there if it has.)
- [ ] Consider asking first in a [Discussion](https://github.com/PKU-Alignment/omnisafe/discussions/new).

### Questions

When I was using omnisafe environment, I followed the documentation to set up a gym-like environment, which uses numpy and gym's self to implement state transfer, and I can successfully use cuda when using stable-baseline3, but omnisafe doesn't support it and throws the following error:  
![image](https://github.com/PKU-Alignment/omnisafe/assets/59566183/0f665b53-cb69-4090-b74d-8b1f04c05a47)
After locating the code, I found the problem:
![image](https://github.com/PKU-Alignment/omnisafe/assets/59566183/c6d6f2a8-a551-4c34-bf85-8fee23427181)
I converted tensor to numpy in order to meet omnisafe's environment normalization requirements when training with cpu, thus eliciting the above error.  But actually my training environment is very complex and I have to use cuda. after trying to consult the docs I still haven't found a solution due to the fact that cuda tensor can't be directly converted to numpy, which requires the above mentioned operation. I don't know if OmniSafe needs to put all parameters on cuda when using it or play back information such as action and state from the experience pool. Thanks for your help.

**Comment by Gaiejj** [comment]
I would like to restate your issues to better focus on the key points:
- You have built a gym-like environment that runs successfully in stable-baselines3.
- Your environment needs to be adapted for OmniSafe, specifically for environment normalization.
- After making changes, you found it cannot support running on CUDA.

I think the following solutions might be feasible:
- Have you specified the device? For example, if your environment runs on `cuda:0`, you should pass the same device when executing `train_policy.py` or using other interfaces.
- What exactly are the environment normalization changes you mentioned, and in which file? I think we can come up with a more compatible modification plan.

**Comment by liu-yuntao** [comment]
Thank you for your response. In fact, first of all we passed in the cuda:0 setting via the parser.add_argument method when using OmniSafe, and cuda:0 is available：
![image](https://github.com/PKU-Alignment/omnisafe/assets/59566183/179f8fbb-f7d2-4484-889c-b5651080b05b)
For environment normalization, the gym-based stable-baseline3 requires that the return value must be numpy, and for this reason we have followed the journey given by OmniSafe in the reset and step functions to tensor：
![image](https://github.com/PKU-Alignment/omnisafe/assets/59566183/129bf35b-6439-4b55-a307-910c77bc17ad)
![image](https://github.com/PKU-Alignment/omnisafe/assets/59566183/1bfcc5cb-9474-4744-9fee-81a34653a826)
![image](https://github.com/PKU-Alignment/omnisafe/assets/59566183/c8dce903-5182-46d3-9d10-a30fcc3dc7b6)
Such a design is perfectly feasible when training with a cpu, and I've reached a preliminary test of the results, but the time overhead required for training is too large.
In fact, we found that the core of the problem now is that the action needs to be converted to numpy first and then the data extracted into the state transfer:
![image](https://github.com/PKU-Alignment/omnisafe/assets/59566183/8ee01b18-824c-4756-a72f-de71aec3085e)
Maybe that's the key to the problem at hand. Thanks for your help.

**Comment by Gaiejj** [comment]
I carefully reviewed the code you provided and found that when you convert numpy arrays to tensors, you did not place them on the appropriate device. You can refer to the approach used in `omnisafe/envs/safety_gymnasium_env.py` and I hope it can be helpful.

**Comment by liu-yuntao** [comment]
Thank you very much for your help, I was missing was neglecting the DEVICE settings and am now able to train with cuda. Another small question is whether omisafe currently supports something like stable-baseline3's “action, _states = RL_model.predict(obs)” for our individually designed test environments for reasoning

**Comment by Gaiejj** [comment]
I understand you want to load the trained model weights into an actor for evaluation. You can give the example script at `examples/evaluate_saved_policy.py` a try. This should help you do that in a straightforward way.

**Comment by liu-yuntao** [comment]
Thank you very much for your patience in replying！

**Comment by Gaiejj** [comment]
Since there has been no response for a long time, we will close this issue. Please feel free to reopen it if you encounter any new problems!
