### ISSUE TITLE
[Question] A question about epoch visualization during the training process

### ISSUE THREAD

**Issue by CrazyTrumpet10** [PKU-Alignment/omnisafe#339]
### Required prerequisites

- [X] I have read the documentation <https://omnisafe.readthedocs.io>.
- [X] I have searched the [Issue Tracker](https://github.com/PKU-Alignment/omnisafe/issues) and [Discussions](https://github.com/PKU-Alignment/omnisafe/discussions) that this hasn't already been reported. (+1 or comment there if it has.)
- [ ] Consider asking first in a [Discussion](https://github.com/PKU-Alignment/omnisafe/discussions/new).

### Questions

![epoch_1](https://github.com/PKU-Alignment/omnisafe/assets/145949900/39388a9e-ff70-4e9d-b0ae-d1faa7891baf)
![1716970569230](https://github.com/PKU-Alignment/omnisafe/assets/145949900/43339b06-9199-46c7-8d30-4c51122ba720)
Hello, my research direction is path planning, I would like to ask how to render the visualization of each epoch trajectory image, check the description of the document does not seem to find the relevant instructions, look forward to your reply, thank you very much!
Every time I render the graph, it is the initialized environment with no trajectories, I also try to get the coordinates of the intelligences for each epoch, and I can get them, but I can't render them in the environment graph, and I would like to ask how to render the trajectories properly?

**Comment by Gaiejj** [comment]
I've grasped your requirement, but currently, OmniSafe doesn't offer an interface for visualizing during the training process or saving rendered videos after each epoch. We acknowledge this as a valuable feature and intend to support it in future updates.

In the meantime, to address your current needs, you might consider saving the model weights at the end of each epoch. 
By setting `save_model_freq` in the algorithm `yaml` file.

Post-training, you can individually load these saved weights and proceed with visualizations. This approach allows you to retrospectively analyze the progress and performance of the model at every stage.

**Comment by Gaiejj** [comment]
Since there has been no response for a long time, we will close this issue. Please feel free to reopen it if you encounter any new problems!
