### ISSUE TITLE
[Question] ValueError: Loaded data does not have the required field "init_obs" for episodic data

### ISSUE THREAD

**Issue by akifumi-wachi-4** [PKU-Alignment/omnisafe#340]
### Required prerequisites

- [X] I have read the documentation <https://omnisafe.readthedocs.io>.
- [X] I have searched the [Issue Tracker](https://github.com/PKU-Alignment/omnisafe/issues) and [Discussions](https://github.com/PKU-Alignment/omnisafe/discussions) that this hasn't already been reported. (+1 or comment there if it has.)
- [X] Consider asking first in a [Discussion](https://github.com/PKU-Alignment/omnisafe/discussions/new).

### Questions

I tried to follow the README in https://github.com/PKU-Alignment/omnisafe/tree/main/benchmarks/offline, but encountered an issue saying that `ValueError: Loaded data does not have the required field "init_obs" for episodic data.` when executing the command for https://github.com/PKU-Alignment/omnisafe/tree/main/benchmarks/offline#run-the-benchmark.
Could you tell me how to resolve this issue?

**Comment by Gaiejj** [comment]
Are you using an existing dataset or collecting a new dataset using an actor to run the offline algorithm? I tried collecting an offline dataset locally and then running `run_experiment_grid.py`, and the training was successful. Please provide more detailed error information and descriptions so that we can help resolve your issue.

**Comment by akifumi-wachi-4** [comment]
Thank you for the response.
I tried exactly the same process written in https://github.com/PKU-Alignment/omnisafe/tree/main/benchmarks/offline.

1. Training agents used to generate data
2. Collect offline data
3. Run the Benchmark

In Step 3, I encountered the error saying `ValueError: Loaded data does not have the required field "init_obs" for episodic data.` I looked into the dataset (i.e., npz file), but there is no field of "init_obs".

OmniSafe version is the latest (0.5.0).

**Comment by akifumi-wachi-4** [comment]
We looked into this error and found that this error is specific to COptDICE implementations. 
In the COptDICE implementation, `init_obs` is used as an input of NNs. For example,
- https://github.com/PKU-Alignment/omnisafe/blob/080e6b828c65902611e86e7436dc47c674cdafd7/omnisafe/algorithms/offline/coptidice.py#L169

However, the `init_obs` filed is not in the offline dataset, which leads to the error.
Could you tell me how to resolve this?

**Comment by akifumi-wachi-4** [comment]
Thank you!! I could successfully run the whole process for Online RL training!
