### ISSUE TITLE
[Question] 使用自定义环境训练，用evaluate_saved_policy评估时，显示ValueError: Pathplanning-v0 is not supported by any environment class

### ISSUE THREAD

**Issue by 5lyf** [PKU-Alignment/omnisafe#341]
### Required prerequisites

- [X] I have read the documentation <https://omnisafe.readthedocs.io>.
- [X] I have searched the [Issue Tracker](https://github.com/PKU-Alignment/omnisafe/issues) and [Discussions](https://github.com/PKU-Alignment/omnisafe/discussions) that this hasn't already been reported. (+1 or comment there if it has.)
- [X] Consider asking first in a [Discussion](https://github.com/PKU-Alignment/omnisafe/discussions/new).

### Questions

 使用自定义环境训练，用evaluate_saved_policy评估时，显示ValueError: Pathplanning-v0 is not supported by any environment class

**Comment by Gaiejj** [comment]
Based on limited information, it is difficult for us to provide an effective answer. I think this might be due to differences in the way your customized environment is registered. Are you using PyPI, or did you install from the source code?

**Comment by Gaiejj** [comment]
Since there has been no response for a long time, we will close this issue. Please feel free to reopen it if you encounter any new problems!
