### ISSUE TITLE
[Question] 请问在训练完成后，是否能够根据观察变量输出智能体的动作，从而对一些实验要求的自定义的性能指标进行测试呢？

### ISSUE THREAD

**Issue by CornfileChase** [PKU-Alignment/omnisafe#343]
### Required prerequisites

- [X] I have read the documentation <https://omnisafe.readthedocs.io>.
- [X] I have searched the [Issue Tracker](https://github.com/PKU-Alignment/omnisafe/issues) and [Discussions](https://github.com/PKU-Alignment/omnisafe/discussions) that this hasn't already been reported. (+1 or comment there if it has.)
- [ ] Consider asking first in a [Discussion](https://github.com/PKU-Alignment/omnisafe/discussions/new).

### Questions

请问在自定义的环境下训练完成后，想输出一些实验中需要测试的性能指标，比如任务成功率，是否允许通过某种方式输出训练完成后的智能体动作呢?或者通过现有的evaluate方法怎么输出一些自定义的性能指标呢？谢谢！

**Comment by Gaiejj** [comment]
You can consider modifying `omnisafe/evaluator.py` to achieve this functionality.

**Comment by CornfileChase** [comment]
Thanks a lot!
