### ISSUE TITLE
evaluate saved_policy

### ISSUE THREAD

**Issue by Eureka725** [PKU-Alignment/omnisafe#344]
### Required prerequisites

- [X] I have read the documentation <https://omnisafe.readthedocs.io>.
- [X] I have searched the [Issue Tracker](https://github.com/PKU-Alignment/omnisafe/issues) and [Discussions](https://github.com/PKU-Alignment/omnisafe/discussions) that this hasn't already been reported. (+1 or comment there if it has.)
- [ ] Consider asking first in a [Discussion](https://github.com/PKU-Alignment/omnisafe/discussions/new).

### Questions

Thank you very much for your work! I would like to inquire about the related issues of `Epcost` and `Epret` stored in the `logger.` The `averagecost` in the `resulting.txt` file generated after `evaluate saved_policy` output video is significantly different from the one stored in the `logger` during the training process. May I ask how to solve this?

**Comment by Gaiejj** [comment]
In fact, they are indeed different. The data recorded in the logger reflects the performance during the training process, while the results.txt records the performance using a deterministic policy after the training has ended.

**Comment by Gaiejj** [comment]
Since there has been no response for a long time, we will close this issue. Please feel free to reopen it if you encounter any new problems!
